questions =  [
    {"id": 0, "question": "Uma economia de mercado é a melhor e mais prática maneira de uma sociedade prosperar.", "effects": {"right": 1}},
    {"id": 1, "question": "Os programas sociais governamentais são um gasto desnecessário que deve ser reduzido.", "effects": {"right": 1}},
    {"id": 2, "question": "Salários são justos, pois o patrão sabe melhor quanto vale o trabalho do empregado.", "effects": {"right": 1}},
    {"id": 3, "question": "A desigualdade econômica é algo inevitável.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Exploração\" é um termo ultrapassado, já que os problemas do capitalismo dos 1800s já foram superados.", "effects": {"right": 1}},
    {"id": 5, "question": "Comunismo é uma ideologia que nunca funcionaria na prática.", "effects": {"right": 1}},
    {"id": 6, "question": "Empresas e serviços estatais deveriam ser privatizados para maior eficiência.", "effects": {"right": 1}},
    {"id": 7, "question": "Taxação sobre grandes fortunas é uma ideia ruim, a sociedade ficaria melhor sem isso.", "effects": {"right": 1}},
    {"id": 8, "question": "Quanto mais duro você trabalha, mais você sobe na pirâmide social.", "effects": {"right": 1}},
    {"id": 9, "question": "Empresas e corporações não são confiáveis e precisam de regulação governamental.", "effects": {"right": -1}},
    {"id": 10, "question": "O Estado deve garantir acesso universal e gratuito aos serviços básicos.", "effects": {"right": -1}},
    {"id": 11, "question": "Grandes heranças deveriam ser fortemente tributadas.", "effects": {"right": -1}},
    {"id": 12, "question": "Terras não deveriam ser mercadorias para serem compradas e vendidas.", "effects": {"right": -1}},
    {"id": 13, "question": "Toda a indústria e bancos deveriam ser nacionalizados.", "effects": {"right": -1}},
    {"id": 14, "question": "A divisão em classes é prejudicial à sociedade.", "effects": {"right": -1}},
    {"id": 15, "question": "A riqueza deveria ser redistribuída.", "effects": {"right": -1}},
    {"id": 16, "question": "A intervenção do Estado é uma ameaça à economia.", "effects": {"right": 1}},
    {"id": 17, "question": "Em algumas situações, é legítimo que o governo espione seus cidadãos para combater extremistas e terroristas.", "effects": {"auth": 1}},
    {"id": 18, "question": "Autoridades fortes, se moralmente corretas, são uma coisa boa para a sociedade.", "effects": {"auth": 1}},
    {"id": 19, "question": "A força é necessária para que qualquer governo tenha sucesso.", "effects": {"auth": 1}},
    {"id": 20, "question": "Somente o Estado é capaz de garantir a ordem.", "effects": {"auth": 1}},
    {"id": 21, "question": "A sociedade requer estrutura e burocracia para funcionar.", "effects": {"auth": 1}},
    {"id": 22, "question": "Documentos de identificação obrigatórios deveriam ser exigidos para garantir a segurança pública.", "effects": {"auth": 1}},
    {"id": 23, "question": "Em tempos de crise, a segurança e a ordem são mais importantes que as liberdades civis.", "effects": {"auth": 1}},
    {"id": 24, "question": "Se você não tem nada a esconder, não tem porque temer vigilância.", "effects": {"auth": 1}},
    {"id": 25, "question": "O governo deveria estar menos envolvido na vida dos cidadãos.", "effects": {"auth": -1}},
    {"id": 26, "question": "Um país só é uma democracia se possuir eleições.", "effects": {"auth": -1}},
    {"id": 27, "question": "A pena de morte deveria existir em alguns casos.", "effects": {"auth": 1}},
    {"id": 28, "question": "O poder do Estado deve ser limitado para preservar as liberdades individuais.", "effects": {"auth": -1}},
    {"id": 29, "question": "O governo deveria se limitar a prover apenas os serviços de emergência e de segurança.", "effects": {"auth": -1}},
    {"id": 30, "question": "O papel da polícia não é proteger a população, mas sustentar a hierarquia social por meio da força.", "effects": {"auth": -1}},
    {"id": 31, "question": "As redes sociais deveriam ser regulamentadas.", "effects": {"auth": 1}},
    {"id": 32, "question": "Dois indivíduos adultos, com consentimento, deveriam poder fazer o que quiserem um com o outro, mesmo que isso contrarie meus valores.", "effects": {"prog": 1}},
    {"id": 33, "question": "Cada indivíduo deveria ter autonomia sobre o próprio corpo.", "effects": {"prog": 1}},
    {"id": 34, "question": "As pessoas devem poder fazer parte de qualquer religião.", "effects": {"prog": 1}},
    {"id": 35, "question": "O aborto deveria ser legalizado.", "effects": {"prog": 1}},
    {"id": 36, "question": "Manter as tradições é importante para a sociedade.", "effects": {"prog": -1}},
    {"id": 37, "question": "Gênero é algo atribuído pela sociedade, não algo da natureza.", "effects": {"prog": 1}},
    {"id": 38, "question": "Leis baseadas em valores culturais, em vez de éticos, não são corretas.", "effects": {"prog": 1}},
    {"id": 39, "question": "A homossexualidade vai contra os meus valores.", "effects": {"prog": -1}},
    {"id": 40, "question": "Os papéis tradicionais de homens e mulheres devem ser superados.", "effects": {"prog": 1}},
    {"id": 41, "question": "As cotas em universidades são fundamentais para corrigir injustiças históricas.", "effects": {"prog": 1}},
    {"id": 42, "question": "Drogas são nocivas e deveriam ser banidas.", "effects": {"prog": -1}},
    {"id": 43, "question": "A transsexualidade deveria ser legalmente reconhecida.", "effects": {"prog": 1}},
    {"id": 44, "question": "Crimes autoinfringentes ainda sim deveriam ser punidos.", "effects": {"prog": -1}},
    {"id": 45, "question": "Multiculturalismo é algo ruim.", "effects": {"prog": -1}},
    {"id": 46, "question": "Os pais deveriam ter controle absoluto sobre os próprios filhos, pois são mais velhos e mais experientes.", "effects": {"prog": -1}},
    {"id": 47, "question": "No sistema criminal, a reabilitação deve ser mais importante do que a punição.", "effects": {"prog": 1}},
    {"id": 48, "question": "A sociedade era melhor antigamente do que hoje.", "effects": {"prog": -1}},
    {"id": 49, "question": "Ninguém consegue ser moral sem religião.", "effects": {"prog": -1}}
];
